#!/usr/bin/env node
/**
 * Fix BOM (UTF-8 byte order mark) in category.json files generated by PowerShell.
 * PowerShell Set-Content -Encoding UTF8 writes BOM; this removes it.
 */
const fs   = require('fs');
const path = require('path');

const sourceDir = process.argv[2] || 'D:\\EzyCV_OUTPUT\\stock-photos';

const entries = fs.readdirSync(sourceDir, { withFileTypes: true })
  .filter(e => e.isDirectory());

let fixed = 0, alreadyOk = 0;

for (const entry of entries) {
  const jsonPath = path.join(sourceDir, entry.name, 'category.json');
  if (!fs.existsSync(jsonPath)) continue;

  const raw = fs.readFileSync(jsonPath);
  // UTF-8 BOM is EF BB BF
  if (raw[0] === 0xEF && raw[1] === 0xBB && raw[2] === 0xBF) {
    const stripped = raw.slice(3);
    fs.writeFileSync(jsonPath, stripped);
    console.log(`Fixed BOM: ${jsonPath}`);
    fixed++;
  } else {
    console.log(`OK (no BOM): ${jsonPath}`);
    alreadyOk++;
  }
}

console.log(`\nDone: ${fixed} fixed, ${alreadyOk} already OK`);
